name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger this on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Use your secret SSH key

    - name: Copy simple.py to EC2
      run: |
        # Ensure the target directory exists on the EC2 instance (with verbose output)
        ssh -v -o StrictHostKeyChecking=no ec2-user@13.60.205.136 'mkdir -p /home/ec2-user/target-folder/'
        
        # Copy the updated simple.py to the EC2 instance with verbose output
        scp -v -o StrictHostKeyChecking=no simple.py ec2-user@13.60.205.136:/home/ec2-user/target-folder/simple.py

