name: Deploy and Run simple.py on EC2 (Max Verbose)

on:
  push:
    branches:
      - main
    paths:
      - simple.py

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: [Verbose -vvv] SCP simple.py to EC2
        run: |
          scp -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            simple.py ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/

      - name: [Verbose -vvv] Run simple.py on EC2
        run: |
          ssh -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "python3 /home/ec2-user/simple.py"
#end
