name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger workflow on push to the main branch
    paths:
      - '**/*.py'  # Only trigger for Python file changes (optional)

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for CI

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2  # Checkout your repo to access files

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  # Set up Docker Buildx

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Store Docker Hub username in secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Store Docker Hub password in secrets

    - name: Build Docker image
      run: |
        docker build -t datahub1998/simple-python-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push datahub1998/simple-python-app:latest

